name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
jobs:
  test-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests for PR/Merged
        if: ${{ github.event_name != 'schedule' }}
        run: npm run test:devSmoke
        env:
          validUsername: ${{ secrets.DEV_VALID_USERNAME }}
          validPassword: ${{ secrets.DEV_VALID_PASSWORD }}
          baseUrl: ${{ secrets.DEV_BASE_URL }}
      - name: Run Playwright tests for schedule
        if: ${{ github.event_name == 'schedule' }}
        run: npm run test:devRegression
        env:
          validUsername: ${{ secrets.DEV_VALID_USERNAME }}
          validPassword: ${{ secrets.DEV_VALID_PASSWORD }}
          baseUrl: ${{ secrets.DEV_BASE_URL }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-dev
          path: playwright-report/
          retention-days: 30
  test-uat:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests for PR/Merged
        if: ${{ github.event_name != 'schedule' }}
        run: npm run test:uatSmoke
        env:
          validUsername: ${{ secrets.UAT_VALID_USERNAME }}
          validPassword: ${{ secrets.UAT_VALID_PASSWORD }}
          baseUrl: ${{ secrets.UAT_BASE_URL }}
      - name: Run Playwright tests for schedule
        if: ${{ github.event_name == 'schedule' }}
        run: npm run test:uatRegression
        env:
          validUsername: ${{ secrets.UAT_VALID_USERNAME }}
          validPassword: ${{ secrets.UAT_VALID_PASSWORD }}
          baseUrl: ${{ secrets.UAT_BASE_URL }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-uat
          path: playwright-report/
          retention-days: 30
  test-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests for PR/Merged
        if: ${{ github.event_name != 'schedule' }}
        run: npm run test:prodSmoke
        env:
          validUsername: ${{ secrets.PROD_VALID_USERNAME }}
          validPassword: ${{ secrets.PROD_VALID_PASSWORD }}
          baseUrl: ${{ secrets.PROD_BASE_URL }}
      - name: Run Playwright tests for schedule
        if: ${{ github.event_name == 'schedule' }}
        run: npm run test:prodSmoke
        env:
          validUsername: ${{ secrets.PROD_VALID_USERNAME }}
          validPassword: ${{ secrets.PROD_VALID_PASSWORD }}
          baseUrl: ${{ secrets.PROD_BASE_URL }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-prod
          path: playwright-report/
          retention-days: 30          